IF
	InParty("C0GULD")
	OR(2)
	Global("C0NPCInterjectTimer","MYAREA",0)
	!RealGlobalTimerExpired("C0NPCInterjectTimer","MYAREA")
	CombatCounter(0)
	Switch("C0GuldrukTL1","MYAREA")
THEN
RESPONSE #0
	SetGlobal("C0GuldrukTL1","MYAREA",1)
	RealSetGlobalTimer("C0NPCInterjectTimer","MYAREA",12)
RESPONSE #1
	SetGlobal("C0GuldrukTL1","MYAREA",2)
	DisplayStringHead("C0GULD",~*sigh* To think the peace of this town would be so horribly ruined...~)
	RealSetGlobalTimer("C0NPCInterjectTimer","MYAREA",2)
END
